server:
  port: 8082
spring:
  data:
    rest:
      basePath: /gate/rest
  profiles: default
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
#        input:
#          group: reservation
#          destination: animal
#          contentType: application/json
        output:
          destination: animal
          contentType: application/json


#feign:
#  hystrix:
#    enabled: true
#
#hystrix:
# command:
#   # 전역설정
#   default:
#     execution.isolation.thread.timeoutInMilliseconds: 610


---
server:
  port: 8080

spring:
  profiles: docker
  data:
    rest:
      basePath: /gate/rest
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.kafka.svc.cluster.local:9092
      bindings:
#        input:
#          group: reservation
#          destination: animal
#          contentType: application/json
        output:
          destination: animal
          contentType: application/json